<div class="filters_panel_white m-b-none-i">
    <form id="filters">
        <date-filter></date-filter>
        <publishers-filter></publishers-filter>
        <advertisers-filter></advertisers-filter>
        <target-geo-countries-filter></target-geo-countries-filter>
        <countries-filter></countries-filter>
        <offers-filter></offers-filter>
        <landings-filter v-show="offer_hashes.length || landing_hashes.length"></landings-filter>
        <transits-filter v-show="offer_hashes.length || transit_hashes.length"></transits-filter>
        <lead-statuses-filter></lead-statuses-filter>
        <currencies-filter></currencies-filter>
        <apply-filters></apply-filters>
    </form>
</div>

<div class="collapse m-b-none-i" id="lead-yet-filters">
    <div class="filters_panel_white m-b-none-i">
        <search-field-filter :search_fields="search_fields" search_fields_width="95px"></search-field-filter>
        <is-autogenerated-filter></is-autogenerated-filter>
    </div>
    <div class="filters_panel_white">
        <div class="filter m-b-none">
            <new-lead></new-lead>
        </div>
    </div>
</div>
<div class="m-b">
    <span class="internal-link" data-toggle="collapse" :data-tab="current_tab"
          data-target="#lead-yet-filters">{{ trans('messages.yet') }}</span>
</div>
